spring:
  application:
    name: opinioncollectorbackend
  datasource:
    username: kambed
    password: kambed
    url: jdbc:postgresql://localhost:5432/opinioncollector
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
jwt:
  variables:
    jwtSecret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3MDc2NjE2NiwiaWF0IjoxNjcwNzY2MTY2fQ.crGTCj7Zw6XJNngC5rRbPPCAD0glbahOayMa0GtynVQ
    jwtExpirationMs: 86400000